name: Deploy Infrastructure & Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'iac/**'
      - 'backend/**'

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      infra: ${{ steps.filter.outputs.infra }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4

      - name: Check which folders changed
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            infra:
              - 'iac/**'
            backend:
              - 'Chair.Api/**'
            
  terraform:
    name: Terraform Plan & Apply
    needs: detect_changes
    if: needs.detect_changes.outputs.infra == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
        contents: read # to fetch workflow files
        id-token: write # for OIDC authentication
    env:
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
          
      - name: Terraform Init
        working-directory: iac
        run: terraform init
        
      - name: Terraform Plan
        working-directory: iac
        run: terraform plan -out=tfplan
      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: iac
        run: terraform apply -auto-approve tfplan

  deploy_api:
    name: Deploy Chair API to Render
    needs: detect_changes
    if: needs.detect_changes.outputs.backend == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Content-Type: application/json"
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{"clearCache":false}' \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys